#!/bin/bash
#logging tool(sensage) checking 
#usage: ./sensage hostlistfile  

#put hostname list file to variable: hostname 
hostname=$1

#Logging(sensage): config files checking: 40-sensage.conf,ksh_audit,sectools.conf
checkfiles() {
	for i in `cat $hostname`; do
	    #print out hostname
	    echo "*** $i ***"

	    #test file: 40-sensage.conf
	    ssh -q -o BatchMode=yes -o StrictHostKeyChecking=no $i [[ -f /etc/rsyslog.d/40-sensage.conf ]]
	    if [ $? -eq 0 ]
	    then
	      echo ">Contents of /etc/rsyslog.d/40-sensage.conf:"
	      ssh -q $i 'sudo /usr/localcw/bin/eksh -c "cat /etc/rsyslog.d/40-sensage.conf"'
	    else
	      echo ">/etc/rsyslog.d/40-sensage.conf not exist"
	    fi

	    #test file: ksh_audit
	    ssh -q $i [[ -f /etc/ksh_audit ]]
	    if [ $? -eq 0 ]
	    then
	      echo ">Contents of /etc/ksh_audit:"
	      ssh -q $i 'sudo /usr/localcw/bin/eksh -c "cat /etc/ksh_audit"'
	    else
	      echo ">/etc/ksh_audit not exist"
	    fi

	    #test file: sectools.conf only allow root access
	    ssh -q $i "sudo /usr/localcw/bin/eksh -c 'test -f /usr/localcw/opt/security/etc/sectools.conf'"
	    if [ $? -eq 0 ]
	    then
	      echo ">Contents of /usr/localcw/opt/security/etc/sectools.conf:"
	      ssh -q $i 'sudo /usr/localcw/bin/eksh -c "cat /usr/localcw/opt/security/etc/sectools.conf"'
	    else
	      echo ">/usr/localcw/opt/security/etc/sectools.conf not exist"
	    fi

	   echo -en '\n'
	done

}

#copy missing file: 40-sensage.conf 
copyfile() {
	for server in `cat $hostname`
	do
	    echo $server
	    cat 40-sensage.conf | ssh -o "BatchMode yes" -q $server "sudo /usr/localcw/bin/eksh -c 'cat - > /etc/rsyslog.d/40-sensage.conf'"
	    ssh -o "BatchMode yes" -q $server "sudo /usr/localcw/bin/eksh -c 'service rsyslog restart'"
	    echo -en '\n'
	done
}


#
# MAIN program
#
IFS='
'
MENU="
check sensage config files 
Copy  missing 40-sensage.conf 
Exit/Stop
"
PS3='Select task:'
select m1 in $MENU
do
case $REPLY in
1) checkfiles;;
2) copyfile;;
3) exit 0 ;;
esac
done
